### ISSUE TITLE
Adopt `./src/<library-module>` folder structure.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/ethereum-python-project-template#14]
See https://blog.ionelmc.ro/2014/05/25/python-packaging/

Suggestion is to locate library source under `./src/<library-name>`

Go read the article for why.  They list lots of compelling reasons.

**Comment by cburgdorf** [comment]
I'm all for it (it's the default layout in the JS/TS/Node world that I come from)

**Comment by carver** [comment]
I'm not sold. I'm not hugely opposed, just not sure it's worth the switch cost. Basically every benefit listed by the article is something independently caught by tox and ci:

> - You get import parity
>   - forced to test the installed code
>   - forced to install the distribution
Caught by tox / CI
> - It prevents you from readily importing your code in the setup.py script
Seems pretty minor, and would be caught early
> - Simpler packaging code and manifest
Nice to have. Our manifests are already quite simple.
> - Without src you get messy editable installs
Nice to have. How often do we have a problem with accidentally importing setup or tests?
> - There are better tools. use tox
Doesn't require this change, already using it
> - https://blog.ionelmc.ro/2014/06/25/python-packaging-pitfalls/
I won't go one by one, but these aren't problems we've been regularly running into.

So it's not exactly that I think it's a bad pattern. More that I'm not seeing enough upside to go convert all our projects to it. It's not necessarily an easy thing to bounty because the will break things besides tests, like our release scripts (and other things I'm not thinking of?).

**Comment by cburgdorf** [comment]
I thought this was mainly about changing the project template to at least benefit for future projects. I agree that this isn't worth it to pursue for existing projects *right now* as we have tons of other work on the table.

**Comment by carver** [comment]
Sure, I was assuming it was also bad to have some projects in one structure and some in another. I guess my recommended rollout strategy would be:

- make the change in one active project
- evaluate the benefits and the drawbacks
- decide whether it's worth the costs
- add to the template, and convert all projects via bounty

My instinct is that the template is not the right place to experiment with new structures.

**Comment by pipermerriam** [comment]
> My instinct is that the template is not the right place to experiment with new structures.

:+1: I opened it here less as a suggestion to change without testing and more as a central location where we could have these discussions.

**Comment by carver** [comment]
> I opened it here less as a suggestion to change without testing and more as a central location where we could have these discussions.

Yeah, an issue in the template seems like a totally reasonable place to have the discussion.

**Comment by davesque** [comment]
I'm also a bit skeptical of this.  I know it's common to use this with a lot of other languages such as JS, C++, etc. but python eschews plenty conventions from the broader software world.  I feel like I've rarely seen a python package that uses this structure.

**Comment by pacrob** [comment]
Closing as old. If someone still has strong feelings, reopen and we can discuss.
